
# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
# from osv import fields,osv --- <8.0.X
from odoo import api, fields, models
from odoo.exceptions import ValidationError
from datetime import date, datetime,timedelta
from odoo import api
from time import time
formatter_string = "%d-%m-%y" 
#from tools.translate import_
#from odoo import tools
import sys
#reload(sys)
#sys.setdefaultencoding("utf-8")
#Importamos la libreria logger
import logging
#Definimos la Variable Global
codigo_ad = ''
_logger = logging.getLogger(__name__)







############################################Estatus del Bien SUDEBIP#############################################################
class estatus_uso(models.Model):
    """Registra el estatus de uso que tiene el Bien"""
    _name = 'estatus_uso'
    #_rec_name = 'estatus_uso_codigo'
    _rec_name = 'estatus_uso_nombre'
    
    estatus_uso_codigo = fields.Char(string='Codigo del Estatus de Uso',size=3,required=True, help='Registra el Codigo de uso del bien')
    estatus_uso_nombre = fields.Char(string='Nombre del Estatus de Uso',size=40,required=True, help='Registra la Descripcion del Estatus de uso del Bien')

    
    _sql_constraints = [('estatus_uso_codigo', 'unique(estatus_uso_codigo)', 'El Código debe se único!')]    
    _sql_constraints = [('estatus_uso_nombre', 'unique(estatus_uso_nombre)', 'El Nombre debe se único!')] 
    
    



class estado_bien(models.Model):
    """Registra el estatus del Bien"""
    _name = 'estado_bien'
    #_rec_name = 'estado_bien_codigo'
    _rec_name = 'estado_bien_nombre'
    

    estado_bien_codigo = fields.Char(string='Codigo del Estado del Bien',size=3,required=True, help='Registra el Codigo del Estado del Bien')
    estado_bien_nombre = fields.Char(string='Nombre del Estado del bien',size=100,required=True, help='Registra la Descripcion del Estado del Bien')

    _sql_constraints = [('estado_bien_codigo', 'unique(estado_bien_codigo)', 'El Código debe se único!')]    
    _sql_constraints = [('estado_bien_nombre', 'unique(estado_bien_nombre)', 'El Nombre debe se único!')] 


class condicion_fisica(models.Model):

    """Registra la condicion fisica Bien"""
    _name = 'condicion_fisica'
   
    _rec_name = 'condicion_fisica_nombre'
    

    condicion_fisica_codigo = fields.Char(string='Codigo de la Condicion Fisica del Bien',size=3,required=True, help='Registra el Codigo de la Condicion Fisica del Bien')
    condicion_fisica_nombre = fields.Char(string='Nombre de la Condicion Fisica del bien',size=100,required=True, help='Registra la Descripcion de la Condicion Fisica del Bien')

    _sql_constraints = [('condicion_fisica_codigo', 'unique(condicion_fisica_codigo)', 'El Código debe se único!')]    
    _sql_constraints = [('condicion_fisica_nombre', 'unique(condicion_fisica_nombre)', 'El Nombre debe se único!')] 





class tipo_bien(models.Model):
    """Registra el tipo de  Bien"""
    _name = 'tipo_bien'
    #_rec_name = ' tipo_bien_codigo'
    _rec_name = 'tipo_bien_nombre'
    
    tipo_bien_codigo = fields.Char(string='Codigo del Tipo de Bien',size=10,required=True, help='Registra el Codigo del Tipo de Bien')
    tipo_bien_nombre = fields.Char(string='Nombre del Tipo de Bien',size=40,required=True, help='Registra la Descripcion del Tipo de Bien')

    
    _sql_constraints = [('tipo_bien_codigo', 'unique(tipo_bien_codigo)', 'El Código debe se único!')]    
    _sql_constraints = [('tipo_bien_nombre', 'unique(tipo_bien_nombre)', 'El Nombre debe se único!')] 


class tipo_bien(models.Model):
    """Registra el tipo de  Bien"""
    _name = 'tipo_bien'
    #_rec_name = ' tipo_bien_codigo'
    _rec_name = 'tipo_bien_nombre'
    
    tipo_bien_codigo = fields.Char(string='Codigo del Tipo de Bien',size=10,required=True, help='Registra el Codigo del Tipo de Bien')
    tipo_bien_nombre = fields.Char(string='Nombre del Tipo de Bien',size=40,required=True, help='Registra la Descripcion del Tipo de Bien')

    
    _sql_constraints = [('tipo_bien_codigo', 'unique(tipo_bien_codigo)', 'El Código debe se único!')]    
    _sql_constraints = [('tipo_bien_nombre', 'unique(tipo_bien_nombre)', 'El Nombre debe se único!')] 


