
# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
# from osv import fields,osv --- <8.0.X
from odoo import api, fields, models

from odoo.exceptions import ValidationError
from datetime import date, datetime,timedelta
from odoo import api
from time import time
formatter_string = "%d-%m-%y" 
#from tools.translate import_
#from odoo import tools
import sys
#reload(sys)
#sys.setdefaultencoding("utf-8")
#Importamos la libreria logger
import logging
#Definimos la Variable Global
codigo_ad = ''
detalle = ''
_logger = logging.getLogger(__name__)




########################################## Registro de Adquisicion del Bien ####################################################################3

class proveedores(models.Model):
    """Registra los Proveedores de los Bienes"""
    _name = 'proveedores'
    #_rec_name = 'proveedores_codigo'
    _rec_name = 'proveedores_nombre'
    #_rec_name = 'rif'
    #_rec_name = 'proveedores_tipo'
    #_rec_name = 'proveedores_observacion'
    

    proveedores_codigo = fields.Char(string='Codigo del Proveedor',size=6,required=True, help='Registra el Codigo del Proveedor del Bien')
    proveedores_nombre = fields.Char(string='Nombre del Proveedor',size=100,required=True, help='Registra el Nombre del Proveedor del Bien')
    rif                = fields.Char(string='Rif del Proveedor',size=20,required=True, help='Registra el RIF del Proveedor del Bien')
    proveedores_tipo   = fields.Selection([('N','Nacional'),('I','Internacional')],string='Tipo de Proveedor', size=1, help='Registra el tipo de proveedor N para nacional I internacional')
    proveedores_observacion = fields.Char(string='Otra Informacion del Proveedor',size=200, help='Registra Otra Informacion del Proveedor del Bien')



    _sql_constraints = [('proveedores_codigo', 'unique(proveedores_codigo)', 'El Código debe se único!')]  
    _sql_constraints = [('proveedores_nombre', 'unique(proveedores_nombre)', 'El Nombre debe se único!')]    
        


class cargo_autoridad(models.Model):
    """Registra la auoridad """
    _name = 'cargo_autoridad'
    #_rec_name = 'uso_inmueble_codigo'
    _rec_name = 'cargo_autoridad_nombre'
    
    cargo_autoridad_codigo = fields.Char(string='Codigo de la Autoridad',size=10,required=True, help='Registra el Codigo del Cargo de la Autoridad')
    cargo_autoridad_nombre = fields.Char(string='Nombre de la Autoridad',size=40,required=True, help='Registra la Descripcion del Cargo de la Autoridad')

    
    _sql_constraints = [('cargo_autoridad_codigo', 'unique(cargo_autoridad_codigo)', 'El Código debe se único!')]    
    _sql_constraints = [('cargo_autoridad_nombre', 'unique(cargo_autoridad_nombre)', 'El Nombre debe se único!')] 









class forma_adquisicion(models.Model):
    """Registra las Formas de Adsquisicion del Bien"""
    _name = 'forma_adquisicion'
    #_rec_name = 'forma_adquisicion_codigo'
    _rec_name = 'forma_adquisicion_nombre'
    forma_adquisicion_codigo = fields.Char(string='Codigo de la Forma de Adquisicion',size=3,required=True, help='Registra el Codigo de la Forma de Adquisicion')
    forma_adquisicion_nombre = fields.Char(string='Nombre de la Forma de Adquisicion',size=100,required=True, help='Registra la descripcion de la forma de adquisicion')
    forma_adquisicion_codigo_origen = fields.Char(string='Codigo del Origen de la Forma de Adquisicion',size=3,required=True, help='Registra el Codigo del Origen de la Forma de Adquisicion')

    _sql_constraints = [('forma_adquisicion_codigo', 'unique(forma_adquisicion_codigo)', 'El Código debe se único!')]  
    _sql_constraints = [('forma_adquisicion_nombre', 'unique(forma_adquisicion_nombre)', 'El Nombre debe se único!')]  




class detalle_adquisi(models.Model):
   """Registra el Detalle de la Adquisicion del bien"""
   _name = 'detalle_adquisi'
   _rec_name = 'detalle_adquisi_codigo'
   #_rec_name = 'forma_adquisi_id'
   #_rec_name = 'nombre_concurso'
   #_rec_name = 'fecha_concurso'
   #_rec_name = 'proveedores_id'
   #_rec_name = 'numero_contrato'
   #_rec_name = 'numero_nota_entrega'
   #_rec_name = 'fecha_nota_entrega'
   #_rec_name = 'numero_factura'
   #_rec_name = 'fecha_factura'
   #_rec_name = 'codigo_pre'
   #_rec_name = 'monto_fact'


#comunes    
    
   fecha_adquisi            = fields.Date(string='Fecha de Adquisición',size=8,  required=True, help='Registra la Fecha de Adquisición  del bien')
   codigo_ori               = fields.Text(string='Código del Origen de Adquisición', size=3)
   codigo_ad                = fields.Text(string='Código de la Forma de Adquisición', size=3)
   detalle_adquisi_codigo   = fields.Char(string='Código del Detalle',size=12,
                              help='Registra el Codigo del Detalle de la Adquisicion del Bien')
   forma_adquisi_id         = fields.Many2one('forma_adquisicion',string='Forma de Adquisición', required=True, help='Registra el Codigo de Vinculacion con las Formas de Adquisicion')
   numero_factura           = fields.Char(string='Numero de Factura',size=15, required=False, help='Registra el Numero de Factura del bien')
   fecha_factura            = fields.Date(string='Fecha de la Factura',size=8,required=False, help='Registra la Fecha de la Factura del bien')
   nombre_registro          = fields.Char(string='Nombre del Registro ',size=100, help='Registra el Nombre del Registro')
   tomo                     = fields.Char(string='Tomo del Registro',size=20, help='Registra el Tomo del Registro')
   folio                    = fields.Integer(string='Folio del Registro',size=6, help='Registra el Folio del Registro ')
   fecha_registro           = fields.Date(string='Fecha de Registro',size=8, help='Registra la Fecha del Registro ')
 
   nombre_organo_emisor     = fields.Char(string='Nombre del Organo Emisor',size=200, help='Registra el Nombre del Organo Emisor')
   nombre_autoridad         = fields.Char(string='Nombre de la  Autoridad',size=50, help='Registra el Nombre de la Autoridad')
   num_sentencia            = fields.Char(string='Número de la Sentencia',size=30, help='Registra el Número de la Sentencia ó Acto Administrativo')
   fecha_sentencia          = fields.Date(string='Fecha de la Sentencia',size=8, help='Registra la Fecha de la Sentencia ó Acto Administrativo')
   nombre_benefici          = fields.Char(string='Nombre del Beneficiario',size=100, help='Registra el Nombre del Beneficiario ')
   nombre_cedente           = fields.Char(string='Nombre del Cedente',size=100, help='Registra el Nombre del Cedente ')
   numero_contrato          = fields.Char(string='Numero de Contrato',size=10, help='Registra el Numero de Contrato  de adquisicion del bien')
   fecha_contrato           = fields.Date(string='Fecha del Contrato',size=8, help='Registra la Fecha del Contrato')
   nombre_donante           = fields.Char(string='Nombre del Donante',size=100, help='Registra el Nombre del Donante')
   estado_autoridad_id      = fields.Many2one('mppp_reg_pro_estados','Entidad Federal',help='Registra La Entidad Federal')
   municipio_autoridad_id   = fields.Many2one('mppp_reg_pro_municipios','Municipio', domain="[('estado_id','=', estado_autoridad_id)]", help='Registra el Municipio')
   tribunal                 = fields.Char(string='Nombre del Tribunal ',size=255, help='Registra el Nombre del Tribunal ')
  
   modalidad_permuta        = fields.Selection([('1','Oferta Pública'),('2','Adjudicación Directa')],string='Modalida de la Permuta', size=1, help='Registra la Modalidad de la Pemuta')
   nombre_licitacion        = fields.Char(string='Nombre de la Licitación ',size=255, help='Registra el Nombre de la Licitación ')
   fecha_licitacion         = fields.Date(string='Fecha  de la Licitación ',size=8, help='Registra la Fecha de la Licitación')   
   numero_licitacion        = fields.Char(string='Número de la Licitación',size=30, help='Registra el Numero de la Licitación ')
   num_decreto              = fields.Char(string='Número del Decreto u Ordenanza',size=10, help='Registra el Número del Decreto u Ordenanza')
   fecha_decreto            = fields.Date(string='Fecha del Decreto u Ordenanza',size=8, help='Registra la Fecha del Decreto u Ordenanza')
   num_bienes               = fields.Char(string='Número de Bienes Transferidos',size=10, help='Registra el Número de Bienes Transferidos')
   nombre_accionista        = fields.Char(string='Nombre del Accionista',size=100, help='Registra el Nombre del Accionista')
   numero_resolucion        = fields.Char(string='Número de la Resolución',size=50, help='Registra el Número de la Resolución')
   fecha_resolucion         = fields.Date(string='Fecha de la Resolución de la Fusión',size=8, help='Registra la Fecha de la Resolución ')
   numero_gaceta            = fields.Integer(string='Número de la Gaceta de Resolución',size=8, help='Registra el Número de la Gaceta de Resolución')
   fecha_gaceta             = fields.Date(string='Fecha de la Gaceta de la Resolución ',size=8, help='Registra la Fecha de la Gaceta de la Resolución')
   numero_registro          = fields.Char(string='Número de Registro',size=20, help='Registra el Número de Registro ')
   tomo_documento            = fields.Char(string='Tomo del Documento Constitutivo',size=20, help='Registra el Tomo del Documento Constitutivo')
   folio_documento           = fields.Char(string='Folio del Documento Constitutivo',size=20, help='Registra el Folio del Documento Constitutivo')
   num_acta                 = fields.Char(string='Número del Acta',size=30, help='Registra el Número del Acta ')
   fecha_acta               = fields.Date(string='Fecha de Acta',size=8, help='Registra la Fecha del Acta ')
   numero_contrato_cesion   = fields.Char(string='Numero de Contrato Cesión',size=10, help='Registra el Numero de Contrato de la Cesión')
   fecha_contrato_cesion    = fields.Date(string='Fecha del Contrato Cesión',size=8, help='Registra la Fecha del Contrato de la Cesión')
   fecha_registro_cesion    = fields.Date(string='Fecha del Registro Cesión',size=8, help='Registra la Fecha del Registro de la Cesión')
   codigo_auto              = fields.Text(string='Código de la Autoridad', size=3)
   cargo_autoridad          = fields.Many2one('cargo_autoridad',string='Cargo de la Autoridad', help='Registra el Cargo de la Autoridad')

   fecha_de_ingreso_bien    = fields.Date(string='Fecha de Ingreso del Bien al Ministerio',size=8, help='Registra la Fecha de la Orden de Compra')

   nombre_prop_ant          = fields.Char(string='Nombre del Propietario Anterior',size=100, help='Registra el Nombre del Propietario Anterior')



#compra
   proveedores_id           = fields.Many2one('proveedores',string='Nombre del Proveedor',  help='Registra el Codigo de Vinculacion con el Proveedor del Bien')
   monto_fact               = fields.Float(string='Monto de la Factura', help='Registra el Monto de la Factura', digits=(20, 7))
   numero_ordcompra         = fields.Char(string='Numero de la Orden de Compra',size=30, help='Registra el Numero de la Orden de Compra del bien')
   fecha_ordcompra          = fields.Date(string='Fecha de la Orden de Compra',size=8, help='Registra la Fecha de la Orden de Compra')


#permuta

   nombre_copermutante      = fields.Char(string='Nombre del Copermutante',size=100, help='Registra el Nombre del Copermutante')
   



#dacion

   numero_finiquito         = fields.Char(string='Número del Finiquito',size=100, help='Registra el Número del Finiquito')
   fecha_finiquito          = fields.Date(string='Fecha del Finiquito',size=8, help='Registra la Fecha del Finiquito')

 

#confiscacion
   nombre_prop_ant_confi    = fields.Char(string='Nombre del Propietario Anterior',size=100, help='Registra el Nombre del Propietario Anterior')
 
  


   _sql_constraints = [('detalle_adquisi_codigo', 'unique(detalle_adquisi_codigo)', 'El Código debe se único!')]    

   @api.onchange('forma_adquisi_id')
   def generar_codigo(self): 
         self.codigo_ad  =  self.forma_adquisi_id.forma_adquisicion_codigo
         self.codigo_ori  =  self.forma_adquisi_id.forma_adquisicion_codigo_origen
  
   @api.onchange('detalle_adquisi_codigo')
   def generar_codigo_deta(self): 
        codigo =   self.codigo_ori 
        detalle =   self.detalle_adquisi_codigo
        if detalle:
          if (len(detalle) < 10):
    
            raise ValidationError("El codigo de detalle de adquisicion no puede ser menor a 10 digitos: %s" % self.detalle_adquisi_codigo) 
          else:
           
            self.detalle_adquisi_codigo= codigo+detalle 
  

   @api.onchange('cargo_autoridad')
   def generar_codigo_auto(self): 
       self.codigo_auto  =  self.cargo_autoridad.cargo_autoridad_codigo
        
         
 

